plugins {
    id 'java'
    id 'application'
    id 'me.champeau.jmh' version '0.7.2'
}

group = 'com.flurry'
version = '0.1.0'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(23) }
}

repositories { mavenCentral() }

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'com.flurry.engine.Main'
}

test { useJUnitPlatform() }

jmh {
    warmupIterations = 3
    iterations = 5
    fork = 1
}